apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: logs-pvc
      containers:
        - name: todo-main
          image: 514sh/todo@sha256:1f904c96be36d525a4508222a3b9b8bf4a12dfd711e01e510bc72dcf18d62d78
          volumeMounts:
          - name: logs
            mountPath: /usr/src/app/logs
        - name: image-uploader
          image: 514sh/image-uploader:1.0.0
          volumeMounts:
          - name: logs
            mountPath: /usr/src/app/logs
